
Vagrant.configure(2) do |config|

  # Handle local proxy settings
  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"] + ',192.168.10.69,10.0.2.15'
    end
  end

  config.vm.hostname = "devstack"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip:"192.168.10.69"
  config.vm.synced_folder "~/", "/vagrant_home"

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = false
    vb.memory = "16800"
    vb.cpus = 2
    override.vm.box = "bento/ubuntu-16.04"

    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
    end

  end

  config.vm.provision :shell do |s|
    s.privileged = false
    s.path = './bootstrap.sh'
    s.args = ENV['PONNY']
  end

end
